# go get github.com/mattn/goreman

etcd4: etcd -name infra4 -listen-client-urls http://localhost:4004 -advertise-client-urls http://localhost:4004 -listen-peer-urls http://localhost:7004 -initial-advertise-peer-urls http://localhost:7004 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://localhost:7001,infra2=http://localhost:7002,infra3=http://localhost:7003,infra4=http://localhost:7004' -initial-cluster-state existing
